name: Test CLI Deploy

on:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-20.04
    env:
      TERM: xterm
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 14
        os:
          - linux
          - macos
          - win
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile --production
      - name: Reset version if needed
        run: |
          git describe --tags --abbrev=1 && yarn bump "$(git describe --tags --abbrev=1 | cut -c2-)" package.json || echo "No tags yet. Skipping..."
          node ./bin/docker-desktop
      - name: Package into node binary
        uses: lando/pkg-action@v2
        with:
          entrypoint: bin/docker-desktop
          arch: ${{ matrix.arch }}
          node-version: node${{ matrix.node-version }}
          os: ${{ matrix.os }}

  sign-n-deploy:
    runs-on: ${{ matrix.os }}
    needs:
      - package
    env:
      TERM: xterm
    strategy:
      matrix:
        include:
          - os: windows-2022
            key: docker-desktop-node14-win-x64-${{ github.sha }}
            file: docker-desktop/docker-desktop.exe
            certificate-data: WINDOZE_CERT_DATA
            certificate-password: WINDOZE_CERT_PASSWORD
            result: docker-desktop-win-x64-snapshot-${{ github.sha }}.exe
          - os: windows-2022
            key: docker-desktop-node14-win-arm64-${{ github.sha }}
            file: docker-desktop/docker-desktop.exe
            certificate-data: WINDOZE_CERT_DATA
            certificate-password: WINDOZE_CERT_PASSWORD
            result: docker-desktop-win-arm64-snapshot-${{ github.sha }}.exe
          - os: macos-11
            key: docker-desktop-node14-macos-x64-${{ github.sha }}
            file: docker-desktop/docker-desktop
            certificate-data: APPLE_CERT_DATA
            certificate-password: APPLE_CERT_PASSWORD
            apple-product-id: dev.lando.docker-desktop
            apple-team-id: FY8GAUX282
            apple-notary-user: APPLE_NOTARY_USER
            apple-notary-password: APPLE_NOTARY_PASSWORD
            options: --options runtime --entitlements entitlements.xml
            result: docker-desktop-macos-x64-snapshot-${{ github.sha }}
          - os: macos-11
            key: docker-desktop-node14-macos-arm64-${{ github.sha }}
            file: docker-desktop/docker-desktop
            certificate-data: APPLE_CERT_DATA
            certificate-password: APPLE_CERT_PASSWORD
            apple-product-id: dev.lando.docker-desktop
            apple-team-id: FY8GAUX282
            apple-notary-user: APPLE_NOTARY_USER
            apple-notary-password: APPLE_NOTARY_PASSWORD
            options: --options runtime --entitlements entitlements.xml
            result: docker-desktop-macos-arm64-snapshot-${{ github.sha }}
          - os: ubuntu-20.04
            key: docker-desktop-node14-linux-x64-${{ github.sha }}
            file: docker-desktop/docker-desktop
            result: docker-desktop-linux-x64-snapshot-${{ github.sha }}
          - os: ubuntu-20.04
            key: docker-desktop-node14-linux-arm64-${{ github.sha }}
            file: docker-desktop/docker-desktop
            result: docker-desktop-linux-arm64-snapshot-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download ${{ matrix.key }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.key }}
          path: docker-desktop
      - name: Sign and Notarize
        uses: lando/code-sign-action@v2
        id: code-sign-action
        with:
          file: ${{ matrix.file }}
          certificate-data: ${{ secrets[matrix.certificate-data] }}
          certificate-password: ${{ secrets[matrix.certificate-password] }}
          apple-notary-user: ${{ secrets[matrix.apple-notary-user] }}
          apple-notary-password: ${{ secrets[matrix.apple-notary-password] }}
          apple-product-id: ${{ matrix.apple-product-id }}
          apple-team-id: ${{ matrix.apple-team-id }}
          options: ${{ matrix.options }}
      - name: Rename as needed
        shell: bash
        run: |
          chmod +x ${{ steps.code-sign-action.outputs.file }}
          mv ${{ steps.code-sign-action.outputs.file }} ${{ matrix.result }}
      - name: Upload snapshot release ${{ matrix.result }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.result }}
          path: ${{ matrix.result }}
          if-no-files-found: error
          retention-days: 1
